version: "3.3"
networks:
  holiday_network:
    driver: overlay
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    environment:
      PROJECT2_DB_URI: ${PROJECT2_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    networks:
    - holiday_network
  service1:
    #image: /service1:latest
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      PROJECT2_DB_URI: ${PROJECT2_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    networks:
    - holiday_network
  service2:
    #image: /service2:latest
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      PROJECT2_DB_URI: ${PROJECT2_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    networks:
    - holiday_network
  service3:
    #image: /service3:latest
    build: ./service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
      PROJECT2_DB_URI: ${PROJECT2_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    networks:
    - holiday_network
  service4:
    #image: /service4:latest
    build: ./service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment: 
      PROJECT2_DB_URI: ${PROJECT2_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    networks:
    - holiday_network