- name: install docker
  hosts: all
  become: true
  roles:
  - docker_install

- name: initialise docker swarm on manager-node
  hosts: localhost
  become: true
  roles:
  - dockerinit

- name: add worker-node to swarm
  hosts: worker
  become: true
  roles:
  - dockerswarm